import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  const AppLocalizations(this.locale);

  static const Map<String, Map<String, String>> _data = {
    'appName': {'ar': 'وصلى', 'en': 'Wasally'},
    'login': {'ar': 'تسجيل الدخول', 'en': 'Login'},
    'register': {'ar': 'إنشاء حساب', 'en': 'Create Account'},
    'home': {'ar': 'الرئيسية', 'en': 'Home'},
    'orders': {'ar': 'طلباتي', 'en': 'My Orders'},
    'wallet': {'ar': 'محفظتي', 'en': 'Wallet'},
    'settings': {'ar': 'الإعدادات', 'en': 'Settings'},
    'profile': {'ar': 'حسابي', 'en': 'Profile'},
    'notifications': {'ar': 'الإشعارات', 'en': 'Notifications'},
    'about': {'ar': 'عن التطبيق', 'en': 'About'},
    'terms': {'ar': 'الشروط والأحكام', 'en': 'Terms & Conditions'},
    'privacy': {'ar': 'سياسة الخصوصية', 'en': 'Privacy Policy'},
    'language': {'ar': 'اللغة', 'en': 'Language'},
    'darkMode': {'ar': 'الوضع الليلي', 'en': 'Dark Mode'},
    'editAccount': {'ar': 'تعديل الحساب', 'en': 'Edit Profile'},
    'changePassword': {'ar': 'تغيير كلمة المرور', 'en': 'Change Password'},
    'logout': {'ar': 'تسجيل الخروج', 'en': 'Logout'},
    'loading': {'ar': 'جارٍ التحميل...', 'en': 'Loading...'},
    'error': {'ar': 'حدث خطأ', 'en': 'Error'},
    'retry': {'ar': 'إعادة المحاولة', 'en': 'Retry'},
    'save': {'ar': 'حفظ', 'en': 'Save'},
    'cancel': {'ar': 'إلغاء', 'en': 'Cancel'},
    'welcome': {'ar': 'مرحباً بك في وصلى', 'en': 'Welcome to Wasally'},
    'loginToContinue': {'ar': 'سجل دخولك للمتابعة', 'en': 'Login to continue'},
    'email': {'ar': 'البريد الإلكتروني', 'en': 'Email'},
    'password': {'ar': 'كلمة المرور', 'en': 'Password'},
    'forgotPassword': {'ar': 'نسيت كلمة المرور؟', 'en': 'Forgot Password?'},
    'noAccount': {'ar': 'ليس لديك حساب؟', 'en': "Don't have an account?"},
    'newOrder': {'ar': 'طلب جديد', 'en': 'New Order'},
    'orderNow': {'ar': 'اطلب دلوقتي', 'en': 'Order Now'},
    'recentOrders': {'ar': 'الطلبات الأخيرة', 'en': 'Recent Orders'},
    'shopFromStores': {'ar': 'تسوق من المتاجر', 'en': 'Shop from Stores'},
    'currentBalance': {'ar': 'الرصيد الحالي', 'en': 'Current Balance'},
    'chargeWallet': {'ar': 'شحن المحفظة', 'en': 'Charge Wallet'},
    'transactions': {'ar': 'سجل المعاملات', 'en': 'Transactions'},
    'noTransactions': {'ar': 'لا توجد معاملات حتى الآن', 'en': 'No transactions yet'},
    'rateOrder': {'ar': 'قيم الطلب', 'en': 'Rate Order'},
    'complaints': {'ar': 'المقترحات والشكاوي', 'en': 'Complaints'},
    'contactAdmin': {'ar': 'تواصل مع الإدارة', 'en': 'Contact Admin'},
    'version': {'ar': 'الإصدار 1.0.0', 'en': 'Version 1.0.0'},
    'customer': {'ar': 'عميل', 'en': 'Customer'},
    'totalOrders': {'ar': 'إجمالي الطلبات', 'en': 'Total Orders'},
    'wasallyPoints': {'ar': 'نقاط وصلى', 'en': 'Wasally Points'},
    'quickOrder': {'ar': 'طلب يدوي', 'en': 'Quick Order'},
    'quickOrderDesc': {'ar': 'اكتب طلبك واحنا نجبلك أي حاجة', 'en': "Write your order and we'll bring it"},
    'arabic': {'ar': 'العربية', 'en': 'Arabic'},
    'english': {'ar': 'الإنجليزية', 'en': 'English'},
    'walletBalance': {'ar': 'رصيد المحفظة', 'en': 'Wallet Balance'},
    'charge': {'ar': 'شحن', 'en': 'Charge'},
    'noOrders': {'ar': 'لا توجد طلبات', 'en': 'No orders'},
    'noRecentOrders': {'ar': 'لا توجد طلبات حديثة', 'en': 'No recent orders'},
    'loadingOrders': {'ar': 'جارٍ تحميل الطلبات...', 'en': 'Loading orders...'},
    'loadingTransactions': {'ar': 'جارٍ تحميل المعاملات...', 'en': 'Loading transactions...'},
    'enterEmail': {'ar': 'أدخل البريد الإلكتروني', 'en': 'Enter email'},
    'enterPassword': {'ar': 'أدخل كلمة المرور', 'en': 'Enter password'},
    'restaurants': {'ar': 'مطاعم', 'en': 'Restaurants'},
    'supermarket': {'ar': 'سوبر ماركت', 'en': 'Supermarket'},
    'pharmacy': {'ar': 'صيدليات', 'en': 'Pharmacy'},
    'electronics': {'ar': 'الكترونيات', 'en': 'Electronics'},
    'clothing': {'ar': 'ملابس', 'en': 'Clothing'},
    'more': {'ar': 'أخری', 'en': 'More'},
    'deposit': {'ar': 'إيداع', 'en': 'Deposit'},
    'withdrawal': {'ar': 'سحب', 'en': 'Withdrawal'},
    'payment': {'ar': 'دفع', 'en': 'Payment'},
    'refund': {'ar': 'استرداد', 'en': 'Refund'},
    'earnings': {'ar': 'أرباح', 'en': 'Earnings'},
    'pending': {'ar': 'قيد الانتظار', 'en': 'Pending'},
    'preparing': {'ar': 'جاري التجهيز', 'en': 'Preparing'},
    'onTheWay': {'ar': 'في الطريق', 'en': 'On the way'},
    'delivered': {'ar': 'تم التسليم', 'en': 'Delivered'},
    'cancelled': {'ar': 'ملغي', 'en': 'Cancelled'},
    'rejected': {'ar': 'مرفوض', 'en': 'Rejected'},
    'assigned': {'ar': 'تم تعيين سائق', 'en': 'Driver assigned'},
    'storeConfirmed': {'ar': 'تم تأكيد المتجر', 'en': 'Store confirmed'},
    'notificationSettings': {'ar': 'الإشعارات', 'en': 'Notifications'},
    'markAllRead': {'ar': 'تحديد الكل كمقروء', 'en': 'Mark all as read'},
    'noNotifications': {'ar': 'لا توجد إشعارات', 'en': 'No notifications'},
    'confirmEmail': {'ar': 'يرجى تأكيد البريد الإلكتروني أولاً. تحقق من بريدك الوارد.', 'en': 'Please confirm your email first. Check your inbox.'},
    'resendConfirmation': {'ar': 'تم إعادة إرسال رابط التأكيد إلى بريدك الإلكتروني', 'en': 'Confirmation link resent to your email'},
    'passwordResetSent': {'ar': 'تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني', 'en': 'Password reset link sent to your email'},
    'resetLinkSent': {'ar': 'تم إرسال رابط إعادة التعيين إلى بريدك', 'en': 'Reset link sent to your email'},
    'errorLoadingBalance': {'ar': 'خطأ في تحميل الرصيد', 'en': 'Error loading balance'},
    'pleaseLogin': {'ar': 'يرجى تسجيل الدخول أولاً', 'en': 'Please login first'},
    'errorLoadingTransactions': {'ar': 'خطأ في تحميل المعاملات', 'en': 'Error loading transactions'},
    'orderHash': {'ar': 'طلب #', 'en': 'Order #'},
    'noOrdersAction': {'ar': 'لا توجد طلبات\nاطلب أول طلب الآن!', 'en': 'No orders yet\nPlace your first order!'},
    'orderTracking': {'ar': 'تتبع الطلب', 'en': 'Order Tracking'},
    'chat': {'ar': 'محادثة', 'en': 'Chat'},
    'loadingOrderData': {'ar': 'جارٍ تحميل بيانات الطلب...', 'en': 'Loading order data...'},
    'errorLoadingOrder': {'ar': 'حدث خطأ أثناء تحميل بيانات الطلب', 'en': 'Error loading order data'},
    'orderNotFound': {'ar': 'الطلب غير موجود', 'en': 'Order not found'},
    'liveTracking': {'ar': 'خريطة التتبع المباشر', 'en': 'Live Tracking Map'},
    'locationNotSet': {'ar': 'الموقع غير محدد', 'en': 'Location not set'},
    'driver': {'ar': 'السائق', 'en': 'Driver'},
    'driverId': {'ar': 'المعرف:', 'en': 'ID:'},
    'connected': {'ar': 'متصل', 'en': 'Connected'},
    'destination': {'ar': 'الوجهة', 'en': 'Destination'},
    'waitingDriverLocation': {'ar': 'بانتظار تحديث موقع السائق...', 'en': 'Waiting for driver location...'},
    'km': {'ar': 'كم', 'en': 'km'},
    'eta': {'ar': 'الوصول المتوقع:', 'en': 'ETA:'},
    'minute': {'ar': 'دقيقة', 'en': 'min'},
    'orderReceived': {'ar': 'تم استلام الطلب', 'en': 'Order Received'},
    'orderReceivedDesc': {'ar': 'تم استلام طلبك بنجاح', 'en': 'Your order has been received'},
    'driverAssigned': {'ar': 'تم تعيين سائق', 'en': 'Driver Assigned'},
    'driverAssignedDesc': {'ar': 'سائق في طريقه لتجهيز طلبك', 'en': 'A driver is on the way to prepare your order'},
    'inDelivery': {'ar': 'جاري التوصيل', 'en': 'In Delivery'},
    'inDeliveryDesc': {'ar': 'السائق في الطريق إليك', 'en': 'The driver is on the way to you'},
    'deliveredDesc': {'ar': 'تم تسليم الطلب بنجاح', 'en': 'Order delivered successfully'},
    'orderStatus': {'ar': 'حالة الطلب', 'en': 'Order Status'},
    'paymentWallet': {'ar': 'الدفع عبر المحفظة', 'en': 'Pay via Wallet'},
    'paymentCash': {'ar': 'الدفع نقداً عند الاستلام', 'en': 'Cash on Delivery'},
    'manualOrder': {'ar': 'طلب يدوي', 'en': 'Manual Order'},
    'thankYouRating': {'ar': 'شكراً لتقييمك', 'en': 'Thanks for rating'},
    'fullName': {'ar': 'الاسم بالكامل', 'en': 'Full Name'},
    'enterName': {'ar': 'أدخل الاسم', 'en': 'Enter name'},
    'phoneNumber': {'ar': 'رقم الهاتف (اختياري)', 'en': 'Phone Number (optional)'},
    'confirmPassword': {'ar': 'تأكيد كلمة المرور', 'en': 'Confirm Password'},
    'passwordMismatch': {'ar': 'كلمة المرور غير متطابقة', 'en': 'Passwords do not match'},
    'passwordMinLength': {'ar': 'كلمة المرور 6 أحرف على الأقل', 'en': 'Password must be at least 6 characters'},
    'agreeTerms': {'ar': 'أوافق على الشروط والأحكام', 'en': 'I agree to the Terms & Conditions'},
    'agreeTermsRequired': {'ar': 'يرجى الموافقة على الشروط والأحكام', 'en': 'Please agree to the Terms & Conditions'},
    'joinWasally': {'ar': 'انضم إلى وصلى', 'en': 'Join Wasally'},
    'emailConfirmationSent': {'ar': 'تم إنشاء الحساب! يرجى التحقق من بريدك الإلكتروني لتأكيد الحساب', 'en': 'Account created! Please check your email to confirm your account'},
    'haveAccount': {'ar': 'لديك حساب؟', 'en': 'Already have an account?'},
    'signIn': {'ar': 'تسجيل دخول', 'en': 'Sign In'},
    'locationDetected': {'ar': 'تم تحديد الموقع', 'en': 'Location detected'},
    'usingDefaultLocation': {'ar': 'تم استخدام موقع افتراضي', 'en': 'Using default location'},
    'orderSentSuccess': {'ar': 'تم إرسال طلبك بنجاح!', 'en': 'Order sent successfully!'},
    'orderAlreadyExists': {'ar': 'هذا الطلب موجود بالفعل', 'en': 'Order already exists'},
    'cannotSendOrderLogin': {'ar': 'لا يمكن إرسال الطلب حالياً، يرجى تسجيل الدخول أولاً', 'en': 'Cannot send order, please login first'},
    'serviceUnavailable': {'ar': 'الخدمة غير متاحة حالياً، حاول مرة أخرى', 'en': 'Service unavailable, try again'},
    'errorSendingOrder': {'ar': 'حدث خطأ أثناء إرسال الطلب، حاول مرة أخرى', 'en': 'Error sending order, try again'},
    'unexpectedError': {'ar': 'حدث خطأ غير متوقع، حاول مرة أخرى', 'en': 'Unexpected error, try again'},
    'newOrderTitle': {'ar': 'طلب جديد - وصلى جابلك', 'en': 'New Order - Wasally Brings It'},
    'quickOrderInfo': {'ar': 'اكتب أي شيء محتاجه - هنوصله لك من أي مكان', 'en': 'Write anything you need - we deliver from anywhere'},
    'orderDetailsField': {'ar': 'تفاصيل الطلب', 'en': 'Order Details'},
    'orderExample': {'ar': 'مثال: 2 كيلو برتقال، علبة حليب، خبز...', 'en': 'Example: 2kg oranges, milk, bread...'},
    'deliveryAddressField': {'ar': 'عنوان التوصيل', 'en': 'Delivery Address'},
    'enterAddressDetail': {'ar': 'اكتب العنوان بالتفصيل', 'en': 'Enter address in detail'},
    'locationSet': {'ar': 'تم تحديد الموقع ✅', 'en': 'Location set ✅'},
    'setMyLocation': {'ar': 'تحديد موقعي الحالي', 'en': 'Set my current location'},
    'sendOrderBtn': {'ar': 'إرسال الطلب', 'en': 'Send Order'},
    'enterOrderDetails': {'ar': 'اكتب تفاصيل طلبك', 'en': 'Enter your order details'},
    'changesSaved': {'ar': 'تم حفظ التغييرات', 'en': 'Changes saved'},
    'saveFailed': {'ar': 'فشل الحفظ', 'en': 'Save failed'},
    'errorOccurred': {'ar': 'حدث خطأ', 'en': 'An error occurred'},
    'editAccountTitle': {'ar': 'تعديل الحساب', 'en': 'Edit Account'},
    'nameField': {'ar': 'الاسم', 'en': 'Name'},
    'nameRequired': {'ar': 'الاسم مطلوب', 'en': 'Name is required'},
    'phoneField': {'ar': 'رقم الهاتف', 'en': 'Phone'},
    'emailField': {'ar': 'البريد الإلكتروني', 'en': 'Email'},
    'addressField': {'ar': 'العنوان', 'en': 'Address'},
    'changePasswordBtn': {'ar': 'تغيير كلمة المرور', 'en': 'Change Password'},
    'loadingPaymentMethods': {'ar': 'جارٍ تحميل طرق الدفع...', 'en': 'Loading payment methods...'},
    'errorLoadingPaymentMethods': {'ar': 'خطأ في تحميل طرق الدفع', 'en': 'Error loading payment methods'},
    'availableChargeMethods': {'ar': 'طرق الشحن المتاحة', 'en': 'Available charge methods'},
    'afterTransferNote': {'ar': 'بعد تحويل المبلغ، سيتم مراجعة العملية وإضافة الرصيد إلى محفظتك من قبل الإدارة', 'en': 'After transferring, the admin will review and add the balance to your wallet'},
    'paymentDataCopied': {'ar': 'تم نسخ بيانات الدفع', 'en': 'Payment data copied'},
    'chargeBtn': {'ar': 'شحن', 'en': 'Charge'},
    'paymentMethod': {'ar': 'طريقة الدفع', 'en': 'Payment method'},
    'cashOnDelivery': {'ar': 'الدفع عند الاستلام', 'en': 'Cash on delivery'},
    'insufficientWalletBalance': {'ar': 'رصيد المحفظة غير كافٍ', 'en': 'Insufficient wallet balance'},
    'walletPaymentFailed': {'ar': 'فشل الدفع من المحفظة', 'en': 'Wallet payment failed'},
    'insufficientBalance': {'ar': 'الرصيد غير كافٍ', 'en': 'Insufficient balance'},
    'insufficientBalanceDesc': {'ar': 'رصيد محفظتك لا يكفي لإتمام الطلب. يرجى شحن المحفظة والمحاولة مرة أخرى.', 'en': 'Your wallet balance is insufficient. Please charge your wallet and try again.'},
    'amount': {'ar': 'المبلغ (ج.م)', 'en': 'Amount (EGP)'},
    'enterAmount': {'ar': 'أدخل المبلغ المراد شحنه', 'en': 'Enter the amount to charge'},
    'amountRequired': {'ar': 'يرجى إدخال المبلغ', 'en': 'Please enter the amount'},
    'amountInvalid': {'ar': 'المبلغ غير صالح', 'en': 'Invalid amount'},
    'transferImage': {'ar': 'صورة التحويل', 'en': 'Transfer screenshot'},
    'uploadImageHint': {'ar': 'يرجى إرفاق صورة واضحة توضح عملية التحويل', 'en': 'Please attach a clear screenshot showing the transfer'},
    'tapToUpload': {'ar': 'اضغط لرفع الصورة', 'en': 'Tap to upload image'},
    'removeImage': {'ar': 'إزالة الصورة', 'en': 'Remove image'},
    'sendingRequest': {'ar': 'جارٍ إرسال الطلب...', 'en': 'Sending request...'},
    'sendRechargeRequest': {'ar': 'إرسال طلب الشحن', 'en': 'Send recharge request'},
    'rechargePendingNote': {'ar': 'بعد الموافقة على طلبك، سيتم إضافة الرصيد إلى محفظتك', 'en': 'After approval, the balance will be added to your wallet'},
    'rechargeRequestSent': {'ar': 'تم إرسال طلب الشحن، سيراجعه الإدارة قريباً', 'en': 'Recharge request sent, admin will review shortly'},
    'done': {'ar': 'تم', 'en': 'Done'},
    'camera': {'ar': 'الكاميرا', 'en': 'Camera'},
    'gallery': {'ar': 'المعرض', 'en': 'Gallery'},
    'attachTransferImage': {'ar': 'يرجى إرفاق صورة التحويل', 'en': 'Please attach a transfer screenshot'},
    'rechargeError': {'ar': 'حدث خطأ', 'en': 'An error occurred'},
    'complaintSuccess': {'ar': 'تم إرسال شكواك بنجاح ✅', 'en': 'Your complaint has been sent successfully ✅'},
    'errorSendingMessage': {'ar': 'حدث خطأ أثناء إرسال الرسالة، حاول مرة أخرى', 'en': 'Error sending message, try again'},
    'complaintsTitle': {'ar': 'المقترحات والشكاوي', 'en': 'Complaints & Suggestions'},
    'complaintInfo': {'ar': 'رسائلك تصل للإدارة مباشرة ونحن نحرص على الرد في أقرب وقت', 'en': 'Your messages go directly to management and we ensure a prompt response'},
    'messageType': {'ar': 'نوع الرسالة', 'en': 'Message type'},
    'complaint': {'ar': 'شكوى', 'en': 'Complaint'},
    'suggestion': {'ar': 'اقتراح', 'en': 'Suggestion'},
    'inquiry': {'ar': 'استفسار', 'en': 'Inquiry'},
    'messageTitle': {'ar': 'عنوان الرسالة', 'en': 'Message title'},
    'description': {'ar': 'الوصف', 'en': 'Description'},
    'send': {'ar': 'إرسال', 'en': 'Send'},
    'rateDriverFirst': {'ar': 'يرجى تقييم السائق', 'en': 'Please rate the driver'},
    'rateAppFirst': {'ar': 'يرجى تقييم التطبيق', 'en': 'Please rate the app'},
    'thanksForRating': {'ar': 'شكراً لتقييمك!', 'en': 'Thanks for rating!'},
    'rateOrderTitle': {'ar': 'تقييم الطلب', 'en': 'Rate Order'},
    'rateYourExperience': {'ar': 'قيم تجربتك', 'en': 'Rate your experience'},
    'shareOpinion': {'ar': 'شاركنا رأيك لتحسين الخدمة', 'en': 'Share your feedback to improve the service'},
    'rateDriver': {'ar': 'تقييم السائق', 'en': 'Rate Driver'},
    'rateApp': {'ar': 'تقييم التطبيق', 'en': 'Rate App'},
    'addComment': {'ar': 'أضف تعليقاً (اختياري)', 'en': 'Add a comment (optional)'},
    'submitRating': {'ar': 'إرسال التقييم', 'en': 'Submit Rating'},
    'selectRating': {'ar': 'اختر تقييماً', 'en': 'Select a rating'},
    'shareOpinionOrder': {'ar': 'شاركنا رأيك في الطلب', 'en': 'Share your opinion about the order'},
    'contactSupport': {'ar': 'التواصل مع الدعم', 'en': 'Contact Support'},
    'supportNotAvailable': {'ar': 'لا يوجد دعم متاح حالياً، سيتم الرد في أقرب وقت', 'en': 'Support not available, we will respond as soon as possible'},
    'connectingSupport': {'ar': 'جاري التوصيل مع خدمة العملاء...', 'en': 'Connecting to support...'},
    'tryAgainLater': {'ar': 'يرجى المحاولة لاحقاً', 'en': 'Please try again later'},
    'aboutApp': {'ar': 'عن التطبيق', 'en': 'About App'},
    'aboutDescription': {'ar': 'تطبيق وصلى هو منصة توصيل طلبات متكاملة تهدف إلى تسهيل عملية توصيل المشتريات والطلبات من المتاجر المختلفة إلى باب منزلك بكل سهولة وأمان. نقدم لك تجربة سلسة وسريعة مع أفضل سائقي التوصيل.', 'en': 'Wasally is a comprehensive delivery platform that makes it easy and safe to deliver purchases and orders from various stores to your doorstep. We offer a smooth, fast experience with the best delivery drivers.'},
    'lastUpdate': {'ar': 'آخر تحديث: 1 يناير 2025', 'en': 'Last updated: January 1, 2025'},
    'intro': {'ar': 'مقدمة', 'en': 'Introduction'},
    'introText': {'ar': 'باستخدامك لتطبيق وصلى، فإنك توافق على هذه الشروط والأحكام. يرجى قراءتها بعناية قبل استخدام الخدمة. إذا كنت لا توافق على أي من هذه الشروط، يرجى عدم استخدام التطبيق.', 'en': 'By using the Wasally app, you agree to these terms and conditions. Please read them carefully before using the service. If you do not agree to any of these terms, please do not use the app.'},
    'services': {'ar': 'الخدمات المقدمة', 'en': 'Services'},
    'servicesText': {'ar': 'يوفر تطبيق وصلى خدمة توصيل الطلبات من المتاجر المختلفة إلى عنوان العميل. نحن نعمل كوسيط بين العميل والمتجر وسائق التوصيل. يتم تحديد تكلفة التوصيل بناءً على المسافة والوزن والخدمات الإضافية.', 'en': 'Wasally provides delivery services from various stores to the customer address. We act as an intermediary between the customer, the store, and the delivery driver. Delivery cost is determined based on distance, weight, and additional services.'},
    'registration': {'ar': 'التسجيل والحساب', 'en': 'Registration & Account'},
    'registrationText': {'ar': 'للاستفادة من خدماتنا، يجب عليك إنشاء حساب. أنت مسؤول عن الحفاظ على سرية معلومات حسابك وكلمة المرور. يجب أن تكون جميع المعلومات المقدمة دقيقة وكاملة. يحق لنا تعليق أو إلغاء حسابك إذا قدمت معلومات غير صحيحة.', 'en': 'To use our services, you must create an account. You are responsible for maintaining the confidentiality of your account and password. All information provided must be accurate and complete. We reserve the right to suspend or cancel your account if you provide incorrect information.'},
    'responsibility': {'ar': 'المسؤولية', 'en': 'Liability'},
    'responsibilityText': {'ar': 'نحن غير مسؤولين عن أي أضرار قد تحدث نتيجة استخدام الخدمة. مسؤوليتنا محدودة بالقانون. لا نتحمل مسؤولية تأخير التوصيل بسبب ظروف خارجة عن إرادتنا. المتجر هو المسؤول عن جودة المنتجات وسلامتها.', 'en': 'We are not liable for any damages resulting from the use of the service. Our liability is limited by law. We are not responsible for delivery delays due to circumstances beyond our control. The store is responsible for product quality and safety.'},
    'cancellationPolicy': {'ar': 'سياسة الإلغاء والاسترجاع', 'en': 'Cancellation & Return Policy'},
    'cancellationText': {'ar': 'يمكنك إلغاء الطلب قبل أن يتم شحنه. بعد الشحن، قد يتم تطبيق رسوم إلغاء. يتم التعامل مع المرتجعات وفقاً لسياسة المتجر. يرجى التواصل مع خدمة العملاء في حال وجود مشكلة مع الطلب.', 'en': 'You can cancel the order before it is shipped. After shipping, cancellation fees may apply. Returns are handled according to the store policy. Please contact customer service if you have an issue with the order.'},
    'termsModification': {'ar': 'تعديل الشروط', 'en': 'Terms Modification'},
    'termsModificationText': {'ar': 'نحتفظ بالحق في تعديل هذه الشروط في أي وقت. سنقوم بإشعارك بأي تغييرات جوهرية عبر البريد الإلكتروني أو من خلال التطبيق. استمرارك في استخدام التطبيق بعد التعديلات يعني موافقتك على الشروط المعدلة.', 'en': 'We reserve the right to modify these terms at any time. We will notify you of any material changes via email or through the app. Your continued use of the app after modifications constitutes acceptance of the modified terms.'},
    'governingLaw': {'ar': 'القانون', 'en': 'Governing Law'},
    'governingLawText': {'ar': 'تخضع هذه الشروط والأحكام وتفسر وفقاً لقوانين جمهورية مصر العربية. أي نزاع ينشأ عن هذه الشروط يتم حله عن طريق التفاوض الودي، وفي حالة عدم التوصل إلى اتفاق يتم رفع الأمر للمحاكم المختصة.', 'en': 'These terms and conditions are governed by and construed in accordance with the laws of the Arab Republic of Egypt. Any dispute arising from these terms shall be resolved through amicable negotiation, and if no agreement is reached, the matter shall be referred to the competent courts.'},
    'privacyIntro': {'ar': 'المقدمة', 'en': 'Introduction'},
    'privacyIntroText': {'ar': 'نحن في تطبيق وصلى نأخذ خصوصيتك على محمل الجد. تصف سياسة الخصوصية هذه كيفية جمع واستخدام وحماية معلوماتك الشخصية عند استخدامك لتطبيقنا.', 'en': 'At Wasally, we take your privacy seriously. This privacy policy describes how we collect, use, and protect your personal information when you use our app.'},
    'infoWeCollect': {'ar': 'المعلومات التي نجمعها', 'en': 'Information We Collect'},
    'infoWeCollectText': {'ar': 'نجمع المعلومات التالية: الاسم الكامل، البريد الإلكتروني، رقم الهاتف، عنوان التوصيل، الموقع الجغرافي، معلومات الدفع، سجل الطلبات، وتفضيلاتك داخل التطبيق.', 'en': 'We collect the following information: full name, email, phone number, delivery address, geographic location, payment information, order history, and your preferences within the app.'},
    'howWeUseInfo': {'ar': 'كيف نستخدم معلوماتك', 'en': 'How We Use Your Information'},
    'howWeUseInfoText': {'ar': 'نستخدم معلوماتك لتقديم وتحسين خدمات التوصيل، معالجة الطلبات والمدفوعات، التواصل معك بخصوص طلباتك، إرسال إشعارات مهمة، تحسين تجربة المستخدم، وتقديم دعم العملاء.', 'en': 'We use your information to provide and improve delivery services, process orders and payments, communicate with you about your orders, send important notifications, improve user experience, and provide customer support.'},
    'infoSharing': {'ar': 'مشاركة المعلومات', 'en': 'Information Sharing'},
    'infoSharingText': {'ar': 'لا نشارك معلوماتك الشخصية مع أطراف ثالثة إلا في الحالات التالية: مع المتاجر وسائقي التوصيل لتلبية طلبك، للامتثال للقانون، لحماية حقوقنا، أو بموافقتك الصريحة.', 'en': 'We do not share your personal information with third parties except in the following cases: with stores and delivery drivers to fulfill your order, to comply with the law, to protect our rights, or with your explicit consent.'},
    'infoSecurity': {'ar': 'أمان المعلومات', 'en': 'Information Security'},
    'infoSecurityText': {'ar': 'نتخذ إجراءات أمنية مناسبة لحماية معلوماتك من الوصول غير المصرح به أو التعديل أو الإفصاح أو التدمير. يتم تشفير البيانات الحساسة باستخدام بروتوكولات آمنة.', 'en': 'We take appropriate security measures to protect your information from unauthorized access, modification, disclosure, or destruction. Sensitive data is encrypted using secure protocols.'},
    'yourRights': {'ar': 'حقوقك', 'en': 'Your Rights'},
    'yourRightsText': {'ar': 'لديك الحق في الوصول إلى معلوماتك الشخصية وتصحيحها أو حذفها. يمكنك إدارة تفضيلات الإشعارات من إعدادات التطبيق. لديك الحق في الاعتراض على معالجة بياناتك.', 'en': 'You have the right to access, correct, or delete your personal information. You can manage notification preferences from the app settings. You have the right to object to the processing of your data.'},
    'cookies': {'ar': 'ملفات تعريف الارتباط', 'en': 'Cookies'},
    'cookiesText': {'ar': 'نستخدم ملفات تعريف الارتباط وتقنيات مشابهة لتحسين تجربتك وتحليل استخدام التطبيق. يمكنك التحكم في استخدام ملفات تعريف الارتباط من إعدادات متصفحك.', 'en': 'We use cookies and similar technologies to improve your experience and analyze app usage. You can control cookie usage through your browser settings.'},
    'contactSection': {'ar': 'التواصل', 'en': 'Contact'},
    'contactSectionText': {'ar': 'إذا كانت لديك أي استفسارات حول سياسة الخصوصية هذه، يرجى التواصل معنا عبر البريد الإلكتروني: privacy@wasally.app', 'en': 'If you have any questions about this privacy policy, please contact us at: privacy@wasally.app'},
    'fillAllFields': {'ar': 'يرجى ملء جميع الحقول', 'en': 'Please fill all fields'},
    'noComplaints': {'ar': 'لا توجد شكاوي', 'en': 'No complaints'},
    'newComplaint': {'ar': 'شكوى جديدة', 'en': 'New complaint'},
    'noMessages': {'ar': 'لا توجد رسائل بعد', 'en': 'No messages yet'},
    'typeMessage': {'ar': 'اكتب رسالتك...', 'en': 'Type your message...'},
    'currencyEGP': {'ar': 'ج.م', 'en': 'EGP'},
    'noInternet': {'ar': 'لا يوجد اتصال بالإنترنت', 'en': 'No internet connection'},
    'checkInternet': {'ar': 'يرجى التحقق من اتصال الهاتف بالإنترنت', 'en': 'Please check your internet connection'},
    'retryConnection': {'ar': 'إعادة المحاولة', 'en': 'Retry'},
    'vodafoneCash': {'ar': 'فودافون كاش', 'en': 'Vodafone Cash'},
    'instapay': {'ar': 'إنستاباي', 'en': 'InstaPay'},
    'orangeCash': {'ar': 'أورانج كاش', 'en': 'Orange Cash'},
    'etisalatCash': {'ar': 'اتصالات كاش', 'en': 'Etisalat Cash'},
    'weCash': {'ar': 'وي كاش', 'en': 'We Cash'},
    'bankTransfer': {'ar': 'تحويل بنكي', 'en': 'Bank Transfer'},
    'bankAccount': {'ar': 'بنك مصر - حساب وصلى', 'en': 'Banque Misr - Wasally Account'},
    'privacyPolicyTitle': {'ar': 'سياسة الخصوصية', 'en': 'Privacy Policy'},
    'termsTitle': {'ar': 'الشروط والأحكام', 'en': 'Terms & Conditions'},
    'invoice': {'ar': 'الفاتورة', 'en': 'Invoice'},
    'createInvoice': {'ar': 'إنشاء فاتورة جديدة', 'en': 'Create New Invoice'},
    'itemName': {'ar': 'اسم الصنف', 'en': 'Item Name'},
    'price': {'ar': 'السعر', 'en': 'Price'},
    'quantity': {'ar': 'الكمية', 'en': 'Quantity'},
    'deliveryFee': {'ar': 'رسوم التوصيل', 'en': 'Delivery Fee'},
    'itemTotal': {'ar': 'إجمالي الأصناف', 'en': 'Items Total'},
    'grandTotal': {'ar': 'الإجمالي الكلي', 'en': 'Grand Total'},
    'saveInvoice': {'ar': 'حفظ الفاتورة', 'en': 'Save Invoice'},
    'invoiceCreated': {'ar': 'تم إنشاء الفاتورة بنجاح', 'en': 'Invoice created successfully'},
    'addAtLeastOneItem': {'ar': 'يرجى إضافة صنف واحد على الأقل', 'en': 'Please add at least one item'},
    'enterItemNameAndPrice': {'ar': 'يرجى إدخال اسم الصنف والسعر', 'en': 'Please enter item name and price'},
    'invoiceStatus': {'ar': 'الحالة: ', 'en': 'Status: '},
    'generateQR': {'ar': 'توليد QR Code للتوصيل', 'en': 'Generate QR Code for Delivery'},
    'editInvoice': {'ar': 'تعديل الفاتورة', 'en': 'Edit Invoice'},
    'customerChat': {'ar': 'محادثة العميل', 'en': 'Customer Chat'},
    'storeChat': {'ar': 'محادثة المتجر', 'en': 'Store Chat'},
    'chatInfo': {'ar': 'يمكنك التواصل مع العميل والمتجر مباشرة عبر المحادثة', 'en': 'You can chat directly with the customer and store'},
    'deliveryAddress': {'ar': 'عنوان التوصيل', 'en': 'Delivery Address'},
    'manualAddress': {'ar': 'العنوان اليدوي', 'en': 'Manual Address'},
    'saveChanges': {'ar': 'حفظ التغييرات', 'en': 'Save Changes'},
    'addItem': {'ar': 'إضافة صنف', 'en': 'Add Item'},
    'addMoreItems': {'ar': 'إضافة أصناف إضافية', 'en': 'Add More Items'},
    'noInvoiceYet': {'ar': 'لم يتم إنشاء فاتورة بعد', 'en': 'No invoice yet'},
    'deleteItem': {'ar': 'حذف', 'en': 'Delete'},
    'customerOrders': {'ar': 'طلبات العملاء', 'en': 'Customer Orders'},
    'storeOrders': {'ar': 'طلبات المتاجر', 'en': 'Store Orders'},
    'orderDetails': {'ar': 'تفاصيل الطلب', 'en': 'Order Details'},
    'orderInfo': {'ar': 'معلومات الطلب', 'en': 'Order Info'},
    'orderNumber': {'ar': 'رقم الطلب', 'en': 'Order ID'},
    'gps': {'ar': 'GPS', 'en': 'GPS'},
    'store': {'ar': 'المتجر', 'en': 'Store'},
    'acceptOrder': {'ar': 'قبول الطلب', 'en': 'Accept Order'},
    'startDelivery': {'ar': 'بدأ التوصيل', 'en': 'Start Delivery'},
    'generateQRForDelivery': {'ar': 'توليد QR للتوصيل', 'en': 'Generate QR for Delivery'},
    'orderUpdatedToast': {'ar': 'تم تحديث حالة الطلب', 'en': 'Order status updated'},
    'orderLoadError': {'ar': 'خطأ في تحميل الطلب', 'en': 'Error loading order'},
    'notAvailable': {'ar': 'غير متاح', 'en': 'Not available'},
    'unknown': {'ar': 'غير معروف', 'en': 'Unknown'},
    'call': {'ar': 'اتصال', 'en': 'Call'},
    'createInvoiceBtn': {'ar': 'إنشاء فاتورة', 'en': 'Create Invoice'},
    'editProfile': {'ar': 'تعديل الحساب', 'en': 'Edit Profile'},
    'profileLoadError': {'ar': 'خطأ في تحميل البيانات', 'en': 'Error loading profile data'},
    'profileNotAvailable': {'ar': 'غير متاح', 'en': 'Not available'},
    'changesSavedToast': {'ar': 'تم حفظ التعديلات', 'en': 'Changes saved'},
    'welcomeDriver': {'ar': 'مرحباً!', 'en': 'Welcome!'},
    'pendingOrders': {'ar': 'لديك %s طلب', 'en': 'You have %s order'},
    'pendingOrdersPlural': {'ar': 'لديك %s طلب', 'en': 'You have %s orders'},
    'noPendingOrders': {'ar': 'لا توجد طلبات معلقة', 'en': 'No pending orders'},
    'waitingForDelivery': {'ar': 'بانتظار التوصيل', 'en': 'Waiting for delivery'},
    'currentOrders': {'ar': 'الطلبات الحالية', 'en': 'Current Orders'},
    'noCurrentOrders': {'ar': 'لا توجد طلبات حالياً', 'en': 'No current orders'},
    'viewAllOrders': {'ar': 'عرض كل الطلبات', 'en': 'View All Orders'},
    'driverAppName': {'ar': 'وصلى سائق', 'en': 'Wasally Driver'},
    'ordersLoadError': {'ar': 'خطأ في تحميل الطلبات', 'en': 'Error loading orders'},
    'allOrders': {'ar': 'كل الطلبات', 'en': 'All Orders'},
    'customerNotifications': {'ar': 'طلبات العملاء', 'en': 'Customer Orders'},
    'storeNotifications': {'ar': 'المتاجر', 'en': 'Stores'},
    'noCustomerNotifications': {'ar': 'لا توجد إشعارات من العملاء', 'en': 'No customer notifications'},
    'noStoreNotifications': {'ar': 'لا توجد إشعارات من المتاجر', 'en': 'No store notifications'},
    'notificationLoadError': {'ar': 'حدث خطأ في تحميل الإشعارات', 'en': 'Error loading notifications'},
    'collections': {'ar': 'التحصيل والتوريد', 'en': 'Collections & Supply'},
    'totalDue': {'ar': 'الإجمالي المستحق', 'en': 'Total Due'},
    'totalSupply': {'ar': 'إجمالي التوريد', 'en': 'Total Supply'},
    'totalConfirmed': {'ar': 'تم تأكيده', 'en': 'Confirmed'},
    'remainingSupply': {'ar': 'المبلغ المتبقي للتوريد', 'en': 'Remaining to supply'},
    'submitSupply': {'ar': 'تقديم توريد', 'en': 'Submit Supply'},
    'supplyDialogDesc': {'ar': 'أدخل المبلغ الذي تريد توريده للإدارة', 'en': 'Enter the amount to submit to management'},
    'submit': {'ar': 'تقديم', 'en': 'Submit'},
    'supplySubmitted': {'ar': 'تم تقديم طلب التوريد بنجاح', 'en': 'Supply request submitted successfully'},
    'collectionHistory': {'ar': 'سجل التحصيل والتوريد', 'en': 'Collection & Supply History'},
    'phone': {'ar': 'الهاتف', 'en': 'Phone'},
    'collectionsAndSupply': {'ar': 'التحصيل والتوريد', 'en': 'Collections & Supply'},
    'storesAndInvoices': {'ar': 'المتاجر والفواتير', 'en': 'Stores & Invoices'},
    'generateQRCode': {'ar': 'توليد QR Code', 'en': 'Generate QR Code'},
    'selectOrderForQR': {'ar': 'أدخل رقم الطلب لتوليد QR Code للتوصيل', 'en': 'Enter order ID to generate QR Code'},
    'generate': {'ar': 'توليد', 'en': 'Generate'},
    'storeInvoiceTitle': {'ar': 'فاتورة متجر', 'en': 'Store Invoice'},
    'storeLabel': {'ar': 'المتجر:', 'en': 'Store:'},
    'cash': {'ar': 'نقدي', 'en': 'Cash'},
    'storeInvoiceSent': {'ar': 'تم إرسال فاتورة المتجر', 'en': 'Store invoice sent'},
    'storesLoadError': {'ar': 'خطأ في تحميل المتاجر', 'en': 'Error loading stores'},
    'noStoresAvailable': {'ar': 'لا توجد متاجر متاحة', 'en': 'No stores available'},
    'storesLoading': {'ar': 'جارٍ تحميل المتاجر...', 'en': 'Loading stores...'},
    'qrDelivery': {'ar': 'QR التوصيل', 'en': 'Delivery QR'},
    'qrLoadError': {'ar': 'خطأ في تحميل البيانات', 'en': 'Error loading data'},
    'qrScanInstruction': {'ar': 'اطلب من العميل مسح هذا الرمز لتأكيد التوصيل', 'en': 'Ask the customer to scan this code to confirm delivery'},
    'orderQRTitle': {'ar': 'QR Code التوصيل', 'en': 'Delivery QR Code'},
    'gpsLocation': {'ar': 'الموقع GPS', 'en': 'GPS Location'},
    'gpsSubtitle': {'ar': 'تشغيل الموقع للتتبع المباشر', 'en': 'Enable location for live tracking'},
    'gpsActivated': {'ar': 'تم تفعيل الموقع', 'en': 'Location activated'},
    'active': {'ar': 'نشط', 'en': 'Active'},
    'driverAppDesc': {'ar': 'تطبيق وصلى هو منصة توصيل طلبات متكاملة تهدف إلى تسهيل عملية توصيل المشتريات والطلبات من المتاجر المختلفة إلى باب العميل بكل سهولة وأمان. نقدم لك تجربة سلسة وسريعة.', 'en': 'Wasally is a comprehensive delivery platform that makes it easy and safe to deliver purchases and orders from various stores to the customer doorstep. We offer a smooth, fast experience.'},
    'driverVersion': {'ar': 'تطبيق السائق', 'en': 'Driver App'},
    'termsIntro': {'ar': 'بتسجيلك كسائق في تطبيق وصلى، أنت توافق على هذه الشروط والأحكام. يرجى قراءتها بعناية قبل استخدام الخدمة.', 'en': 'By registering as a driver in the Wasally app, you agree to these terms and conditions. Please read them carefully before using the service.'},
    'termsServices': {'ar': 'تقديم خدمات التوصيل للعملاء وفقاً للطلبات المخصصة لك. نحن نعمل كوسيط بين العميل والمتجر وسائق التوصيل.', 'en': 'Providing delivery services to customers according to orders assigned to you. We act as an intermediary between the customer, the store, and the delivery driver.'},
    'termsResponsibilities': {'ar': 'الالتزام بمواعيد التوصيل\nالمحافظة على جودة الخدمة\nتحديث حالة الطلب باستمرار\nتحصيل المبالغ النقدية من العملاء', 'en': 'Commit to delivery times\nMaintain service quality\nUpdate order status continuously\nCollect cash payments from customers'},
    'termsCollections': {'ar': 'أنت مسؤول عن تحصيل المبالغ النقدية من العملاء. يجب توريد المبالغ المحصلة للإدارة. يتم توثيق كل عملية تحصيل وتوريد.', 'en': 'You are responsible for collecting cash from customers. Collected amounts must be submitted to management. Every collection and supply is documented.'},
    'termsCommission': {'ar': 'تطبق عمولة على كل طلب يتم توصيله حسب الاتفاق مع الإدارة.', 'en': 'A commission applies to each delivered order as agreed with management.'},
    'termsTermination': {'ar': 'تحتفظ الإدارة بحق إنهاء الخدمة في حال الإخلال بالشروط.', 'en': 'Management reserves the right to terminate service in case of breach of terms.'},
    'termsUpdated': {'ar': 'آخر تحديث: 1 يونيو 2025', 'en': 'Last updated: June 1, 2025'},
    'changePasswordTitle': {'ar': 'تغيير كلمة المرور', 'en': 'Change Password'},
    'newPassword': {'ar': 'كلمة المرور الجديدة', 'en': 'New Password'},
    'confirmNewPassword': {'ar': 'تأكيد كلمة المرور الجديدة', 'en': 'Confirm New Password'},
    'passwordChangedToast': {'ar': 'تم تغيير كلمة المرور بنجاح', 'en': 'Password changed successfully'},
    'aboutDriverApp': {'ar': 'وصلى - تطبيق السائق', 'en': 'Wasally - Driver App'},
  };

  String get(String key) => _data[key]?[locale.languageCode] ?? _data[key]?['ar'] ?? key;

  bool get isEn => locale.languageCode == 'en';
  bool get isAr => locale.languageCode == 'ar';
  TextDirection get textDirection => isAr ? TextDirection.rtl : TextDirection.ltr;
}
